stages:
  - test
  - build
  - uat
  - prod

test:
  stage: test
  image: node:alpine
  cache:
    paths:
      - node_modules/
  script:
   - npm install
   - npm test
   #TODO: add sonarqube

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

uat:
  stage: uat
  image: cypress/base:latest
  services:
    - docker:dind
  script:
    - docker run blablub
    #flightcheck
    - npm install
    - npm run cy:verify
    - npm run uat

prod:
  stage: prod
  script:
    - docker run blabla
    #flightcheck