resources:
- repo: self

jobs:

- job: Job_1
  displayName: gui
  condition: succeeded()
  pool:
    vmImage: Hosted Ubuntu 1604
    demands: npm

  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: services/gui
      verbose: false

  - task: Npm@1
    displayName: 'npm test'
    inputs:
      command: custom
      workingDir: services/gui
      verbose: false
      customCommand: test

  - task: Docker@0
    displayName: 'Build an image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: dockerhub
      dockerFile: services/gui/Dockerfile

  - task: Docker@0
    displayName: 'Push an image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: dockerhub
      action: 'Push an image'


- job: Job_2
  displayName: ketchup
  condition: succeeded()
  pool:
    vmImage: Hosted Ubuntu 1604
    demands: npm

  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: services/ketchup
      verbose: false

  - task: Npm@1
    displayName: 'npm test'
    inputs:
      command: custom
      workingDir: services/ketchup
      verbose: false
      customCommand: test

  - task: Docker@0
    displayName: 'Build an image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: dockerhub
      dockerFile: services/ketchup/Dockerfile

  - task: Docker@0
    displayName: 'Push an image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: dockerhub
      action: 'Push an image'