apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui-{{ template "branchName" . }}-{{ .Values.stage }}
  labels:
    app: gui-{{ template "branchName" . }}-{{ .Values.stage }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gui-{{ template "branchName" . }}-{{ .Values.stage }}
  template:
    metadata:
      labels:
        app: gui-{{ template "branchName" . }}-{{ .Values.stage }}
    spec:
      containers:
      - name: gui-{{ template "branchName" . }}-{{ .Values.stage }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: KETCHUP_ENDPOINT
          value: 'ketchup-{{ template "branchName" . }}-{{ .Values.stage }}'