apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui-{{ template "branchName" . }}-{{ .Values.stage }}
  labels:
    app: gui-{{ template "branchName" . }}-{{ .Values.stage }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui-{{ template "branchName" . }}-{{ .Values.stage }}
  template:
    metadata:
      labels:
        app: gui-{{ template "branchName" . }}-{{ .Values.stage }}
    spec:
      containers:
      - name: gui-{{ template "branchName" . }}-{{ .Values.stage }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        env:
        - name: KETCHUP_ENDPOINT
          value: 'ketchup-{{ template "branchName" . }}-{{ .Values.stage }}'
        - name: NODE_ENV
          value: '{{ .Values.stage }}'
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: moveez-prod-db
              key: dbuser
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: moveez-prod-db
              key: dbpass
        - name: FACEBOOK_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: moveez-prod-facebook
              key: appsecret
      imagePullSecrets:
      - name: acr-auth