apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui-deploy
  labels:
    app: gui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
      - name: gui
        image: moveez.azurecr.io/gui
        ports:
        - containerPort: 8080