apiVersion: apps/v1
kind: Deployment
metadata:
  name: ketchup-13-rottentomato
  labels:
    app: ketchup-13-rottentomato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ketchup-13-rottentomato
  template:
    metadata:
      labels:
        app: ketchup-13-rottentomato
    spec:
      containers:
      - name: ketchup-13-rottentomato
        image: moveez.azurecr.io/ketchup
        ports:
        - containerPort: 80