kind: Service
apiVersion: v1
metadata:
  name: ketchup-{{ template "branchName" . }}-{{ .Values.stage }}
spec:
  selector:
    app: ketchup-{{ template "branchName" . }}-{{ .Values.stage }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80