apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wildcardprod
spec:
  secretName: wildcardprod
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: '*.moveez.de'
  dnsNames:
  - moveez.de
  acme:
    config:
    - dns01:
        provider: azure-dns
        ingressClass: nginx
      domains:
      - '*.moveez.de'
      - moveez.de