apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: schdief.law@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    # Use dns-01 challenges in order to support wildcard domain names
    dns01:
      providers:
      - name: azure-dns
        azuredns:
          email: schdief.law@gmail.com
          # Service principal client id
          clientID: 41627dfb-f091-43ec-805d-9fbb126e37c8
          # Secret with the password
          clientSecretSecretRef:
            name: azuredns-config
            key: CLIENT_SECRET
          # Name of the DNS Zone
          hostedZoneName: moveez.de
          # Resource group where the DNS Zone is located
          resourceGroupName: moveez
          subscriptionID: 0848c798-131c-4d65-ac2c-05b606da73e5
          tenantID: 9d7c1232-54eb-4de0-9a33-49d892328766