pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  batch: true
  branches:
    include: 
    - refs/heads/*
  paths:
    include: 
    - services/gui/

variables:
  registryServerName: '$(registryName).azurecr.io'
  imageName: '$(projectName)'
  # define 5 more variables: projectName, tenantId, registryName, registryLogin and registryPassword in the build pipeline in UI

steps:
- bash: docker build -f $(system.defaultWorkingDirectory)/services/$(projectName)/Dockerfile -t $(registryServerName)/$(imageName):$(build.buildNumber)_$(build.sourceBranchName) -t $(registryServerName)/$(imageName):latest $(system.defaultWorkingDirectory)/services/$(projectName)
  displayName: 'docker build'

- bash: docker login $(registryServerName) -u $(registryLogin) -p $(registryPassword)
  displayName: 'docker login'

- bash: |
    docker push $(registryServerName)/$(imageName):$(build.buildNumber)_$(build.sourceBranchName)
    docker push $(registryServerName)/$(imageName):latest
  displayName: 'docker push'
  #condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))

- task: HelmInstaller@0
  displayName: 'Install Helm'
  inputs:
    helmVersion: 2.12.3

- bash: sed -i 's/ketchup/ketchup_$(build.sourceBranchName)/g' $(system.defaultWorkingDirectory)/services/$(projectName)/charts/$(projectName)/Chart.yaml
  displayName: 'update Chart.yaml with branch name'

- bash: mv $(system.defaultWorkingDirectory)/services/$(projectName)/charts/$(projectName) $(system.defaultWorkingDirectory)/services/$(projectName)/charts/$(projectName)_$(build.sourceBranchName)
  displayName: 'renaming chart folder to match Chart.yaml name'

- bash: helm package --version $(build.buildNumber) --destination $(build.artifactStagingDirectory) $(system.defaultWorkingDirectory)/services/$(projectName)/charts/$(projectName)
  displayName: 'helm package'
  
- bash: az login --service-principal -u $(registryLogin) -p $(registryPassword) -t $(tenantId)
  displayName: 'az login'

- bash: az acr helm push -n $(registryName) -u $(registryLogin) -p $(registryPassword) $(build.artifactStagingDirectory)/$(projectName)-$(build.buildNumber).tgz
  displayName: 'az acr helm push'
  #condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))